guest_list = ["famous_person_a", "famous_person_b", "famous_person_c", "famous_person_d"]
message = f"I am sorry folks, {guest_list[0].title()} can't attend the party"
print(message)
guest_list[0] = "famous_person_a_prime"
print(f"Instead, we'll have the honor of dining with {guest_list[0].title()}")
print(f"Hello, {guest_list[1].title()}, I hope you can make it to the party :)")
print(f"Hello, {guest_list[2].title()}, I hope you can make it to the party :)")
print(f"Hello, {guest_list[3].title()}, I hope you can make it to the party :)")
print("Hello everyone, I've got good news! We found a bigger table and have room for more guests!")
guest_list.insert(0, "start_someone_1")
guest_list.insert(2, "middle_someone_2")
guest_list.append("last_someone_3")
print(f"Hello, {guest_list[0].title()}, I hope you can come tonight ;)")
print(f"Hello, {guest_list[2].title()}, I hope you can come tonight ;)")
print(f"Hello, {guest_list[-1].title()}, I hope you can come tonight ;)")
print(guest_list)
print("Horrible news, we only have two spots...")
popped_guest = guest_list.pop()
print(f"I'm sorry, {popped_guest.title()},I don't have room for you")
popped_guest = guest_list.pop()
print(f"I'm sorry, {popped_guest.title()},I don't have room for you")
popped_guest = guest_list.pop()
print(f"I'm sorry, {popped_guest.title()},I don't have room for you :/")
popped_guest = guest_list.pop()
print(f"I'm sorry, {popped_guest.title()},I don't have room for you :/")
popped_guest = guest_list.pop()
print(f"I'm sorry, {popped_guest.title()},I don't have room for you ")
print(len(guest_list))