visiting = ["Japan", "Morocco", "Greece", "US", "Canada"]
print(visiting)
print(sorted(visiting))
print(visiting)
print(sorted(visiting, reverse=True))
print(visiting)
visiting.reverse()
print(visiting)
visiting.reverse()
print(visiting)
visiting.sort()
print(visiting)
visiting.sort(reverse=True)
print(visiting)